# Email 邮件服务配置
spring:
  mail:
    host: smtp.163.com
    username: 17575010142@163.com
    password: YOUR_EMAIL_AUTH_CODE_HERE
    port: 465
    properties:
      from: 17575010142@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
